### ISSUE TITLE
promo material for GCC ?

### ISSUE THREAD

**Issue by hrhotz** [usegalaxy-eu/european-galaxy-days-2018#1]
shall we print out the logos (I have just uploaded, what we have on galaxy-hub) as promotional material and bring it to GCC? - like we did in 2016 and before.

**Comment by bgruening** [comment]
Yes! :)

**Comment by hrhotz** [comment]
I have printed 80 flyers (and uploaded the pdf I used)

**Comment by bgruening** [comment]
Wonderful!
