### ISSUE TITLE
registration process

### ISSUE THREAD

**Issue by hrhotz** [usegalaxy-eu/european-galaxy-days-2018#3]
I suggest to open registration in late August, with a simple google form page.

Unlike in previous years, we should only ask for name, affiliation, e-mail address, and whether participants want to attend both or only one day.

Combining the registration with a call for speakers was not very successful in 2014 and 2016. We should contact potential speakers directly and/or make a call for talks/presentations separately.

**Comment by bgruening** [comment]
Sounds good.

**Comment by hrhotz** [comment]
maybe we can add a question asking for the level of familiarity with Galaxy?
