### ISSUE TITLE
Website?

### ISSUE THREAD

**Issue by hexylena** [usegalaxy-eu/european-galaxy-days-2018#5]
Does this repo need a website? I can copy paste one of our jekyll templates if we needed something basic to point users to, "here for schedule, here for reg, ..."

**Comment by bgruening** [comment]
Yes, it does. But we can also use usegagalaxy.eu for this. Some event site?

**Comment by hexylena** [comment]
Sure, I was imagining this + gcc2019 might want websites like https://gcc2016.iu.edu/

There are multiple ways to accomplish this:

- build it straight into usegalaxy-eu.github.io
- build a separate site for this repo

No matter what we do, it can be under usegalaxy.eu/galaxy-days-2018 or whatever y'all want. For gcc2019 it should probably be a stand alone website since that's what everyone else does.

**Comment by hrhotz** [comment]
we already have a website (or at least a URL): https://galaxyproject.org/events/2018-europe-dev/
Please stick to this URL, since this URL has already been promoted via ad in GCC2018 booklet, twitter, slides, etc. It is also the URL which is linked from the events page

**Comment by hexylena** [comment]
Ah that's pretty bare, but if this meets the needs of everyone then perfect, I'll close this. (We could redirect if y'all wanted something different later, that's easily done.)
